// Mapping of audio file names to static require calls
export const audioAssets: { [key: string]: any } = {
  // Root audio files
  'route101_stop1.mp3': require('../assets/audio/route101_stop1.mp3'),
  'route101_stop2.mp3': require('../assets/audio/route101_stop2.mp3'),

  // HydStops audio files
  '1.Choutuppal.mp3': require('../assets/audio/HydStops/1.Choutuppal.mp3'),
  '2.ramojifilmcity1.mp3': require('../assets/audio/HydStops/2.ramojifilmcity1.mp3'),
  '3.hayathnagar.mp3': require('../assets/audio/HydStops/3.hayathnagar.mp3'),
  '4.Vanasthalipuram.mp3': require('../assets/audio/HydStops/4.Vanasthalipuram.mp3'),
  '5.LBnagar.mp3': require('../assets/audio/HydStops/5.LBnagar.mp3'),
  '6.kothapeta.mp3': require('../assets/audio/HydStops/6.kothapeta.mp3'),
  '7.dilsuknagar.mp3': require('../assets/audio/HydStops/7.dilsuknagar.mp3'),
  '8.chaithanyapuri.mp3': require('../assets/audio/HydStops/8.chaithanyapuri.mp3'),
  '9.TVTOWERMALAKPET.mp3': require('../assets/audio/HydStops/9.TVTOWERMALAKPET.mp3'),
  '10.koti.mp3': require('../assets/audio/HydStops/10.koti.mp3'),
  '11.abids.mp3': require('../assets/audio/HydStops/11.abids.mp3'),
  '12.nampally.mp3': require('../assets/audio/HydStops/12.nampally.mp3'),
  '13.lakdikapool.mp3': require('../assets/audio/HydStops/13.lakdikapool.mp3'),
  '14.khairathabad.mp3': require('../assets/audio/HydStops/14.khairathabad.mp3'),
  '15.panjaguta.mp3': require('../assets/audio/HydStops/15.panjaguta.mp3'),
  '16.ameerpet.mp3': require('../assets/audio/HydStops/16.ameerpet.mp3'),
  '17.srnagar.mp3': require('../assets/audio/HydStops/17.srnagar.mp3'),
  '18.ESI.mp3': require('../assets/audio/HydStops/18.ESI.mp3'),
  '19.erragada.mp3': require('../assets/audio/HydStops/19.erragada.mp3'),
  '20.bharthnaagar.mp3': require('../assets/audio/HydStops/20.bharthnaagar.mp3'),
  '21.moosapet.mp3': require('../assets/audio/HydStops/21.moosapet.mp3'),
  '22.kukatpally.mp3': require('../assets/audio/HydStops/22.kukatpally.mp3'),
  '23.vivekanandanagar.mp3': require('../assets/audio/HydStops/23.vivekanandanagar.mp3'),
  '24.kphb.mp3': require('../assets/audio/HydStops/24.kphb.mp3'),
  '25.jntu.mp3': require('../assets/audio/HydStops/25.jntu.mp3'),
  '26.nizampet.mp3': require('../assets/audio/HydStops/26.nizampet.mp3'),
  '27.hydernagar.mp3': require('../assets/audio/HydStops/27.hydernagar.mp3'),
  '28.miyapur.mp3': require('../assets/audio/HydStops/28.miyapur.mp3'),
  '29.miyapurallwynXroad.mp3': require('../assets/audio/HydStops/29.miyapurallwynXroad.mp3'),
  '30.madinaguda.mp3': require('../assets/audio/HydStops/30.madinaguda.mp3'),
  '31.gangaram.mp3': require('../assets/audio/HydStops/31.gangaram.mp3'),
  '32.chandanagar.mp3': require('../assets/audio/HydStops/32.chandanagar.mp3'),
  '33.lingampally.mp3': require('../assets/audio/HydStops/33.lingampally.mp3'),
  '34.bhel.mp3': require('../assets/audio/HydStops/34.bhel.mp3'),

  // ST-12 audio files
  '1vijayawada.mp3': require('../assets/audio/ST-12/1vijayawada.mp3'),
  '2gannavaram.mp3': require('../assets/audio/ST-12/2gannavaram.mp3'),
  '3telaprolu.mp3': require('../assets/audio/ST-12/3telaprolu.mp3'),
  '4veeravali.mp3': require('../assets/audio/ST-12/4veeravali.mp3'),
  '5Hanumanjunction.mp3': require('../assets/audio/ST-12/5Hanumanjunction.mp3'),
  '6chebrolu.mp3': require('../assets/audio/ST-12/6chebrolu.mp3'),
  '7eluru.mp3': require('../assets/audio/ST-12/7eluru.mp3'),
  '8denduluru.mp3': require('../assets/audio/ST-12/8denduluru.mp3'),
  '9gundugolunu.mp3': require('../assets/audio/ST-12/9gundugolunu.mp3'),
  '10bhimadolu.mp3': require('../assets/audio/ST-12/10bhimadolu.mp3'),
  '11kurrelagudem.mp3': require('../assets/audio/ST-12/11kurrelagudem.mp3'),
  '12pulla.mp3': require('../assets/audio/ST-12/12pulla.mp3'),
  '13kaikaram.mp3': require('../assets/audio/ST-12/13kaikaram.mp3'),
  '14narayanapuram.mp3': require('../assets/audio/ST-12/14narayanapuram.mp3'),
  '15unguturu.mp3': require('../assets/audio/ST-12/15unguturu.mp3'),
  '16tpgudem.mp3': require('../assets/audio/ST-12/16tpgudem.mp3'),
  '17duva.mp3': require('../assets/audio/ST-12/17duva.mp3'),
  '18tanuku.mp3': require('../assets/audio/ST-12/18tanuku.mp3'),
  '19peravali.mp3': require('../assets/audio/ST-12/19peravali.mp3'),
  '20annavarapadu.mp3': require('../assets/audio/ST-12/20annavarapadu.mp3'),
  '21sidhantham.mp3': require('../assets/audio/ST-12/21sidhantham.mp3'),
  '22ethakota.mp3': require('../assets/audio/ST-12/22ethakota.mp3'),
  '23ravulapalem.mp3': require('../assets/audio/ST-12/23ravulapalem.mp3'),
  '24jonnada.mp3': require('../assets/audio/ST-12/24jonnada.mp3'),
  '25alamuru.mp3': require('../assets/audio/ST-12/25alamuru.mp3'),
  '26kothuru.mp3': require('../assets/audio/ST-12/26kothuru.mp3'),
  '27mandapeta.mp3': require('../assets/audio/ST-12/27mandapeta.mp3'),
  '28Machavaram.mp3': require('../assets/audio/ST-12/28Machavaram.mp3'),
  '29Ramachandrapuram.mp3': require('../assets/audio/ST-12/29Ramachandrapuram.mp3'),
  '30draksharamam.mp3': require('../assets/audio/ST-12/30draksharamam.mp3'),
  '31gollapalem.mp3': require('../assets/audio/ST-12/31gollapalem.mp3'),
  '32kakinada.mp3': require('../assets/audio/ST-12/32kakinada.mp3'),

  // ST-122 audio files
  // '1vijayawada.mp3': require('../assets/audio/ST-122/1vijayawada.mp3'),
  // '2gannavaram.mp3': require('../assets/audio/ST-122/2gannavaram.mp3'),
  '3Hanuman junction.mp3': require('../assets/audio/ST-122/3Hanuman junction.mp3'),
  '4eluru.mp3': require('../assets/audio/ST-122/4eluru.mp3'),
  '5gundugolunu.mp3': require('../assets/audio/ST-122/5gundugolunu.mp3'),
  '6denduluru.mp3': require('../assets/audio/ST-122/6denduluru.mp3'),
  '7bhimadolu.mp3': require('../assets/audio/ST-122/7bhimadolu.mp3'),
  '8dobacherla.mp3': require('../assets/audio/ST-122/8dobacherla.mp3'),
  '9nallajerla.mp3': require('../assets/audio/ST-122/9nallajerla.mp3'),
  '10ananthapalli.mp3': require('../assets/audio/ST-122/10ananthapalli.mp3'),
  '11yerrannagudem.mp3': require('../assets/audio/ST-122/11yerrannagudem.mp3'),
  '12devarapali.mp3': require('../assets/audio/ST-122/12devarapali.mp3'),
  '13dudhukuru.mp3': require('../assets/audio/ST-122/13dudhukuru.mp3'),
  '14gowripatnam.mp3': require('../assets/audio/ST-122/14gowripatnam.mp3'),
  '15pangidi.mp3': require('../assets/audio/ST-122/15pangidi.mp3'),
  '16kovuru.mp3': require('../assets/audio/ST-122/16kovuru.mp3'),
  '17rajahmundry.mp3': require('../assets/audio/ST-122/17rajahmundry.mp3'),
  '18vemagiri.mp3': require('../assets/audio/ST-122/18vemagiri.mp3'),
  '19kadiyam.mp3': require('../assets/audio/ST-122/19kadiyam.mp3'),
  '20kesavaram.mp3': require('../assets/audio/ST-122/20kesavaram.mp3'),
  '21dwarapudi.mp3': require('../assets/audio/ST-122/21dwarapudi.mp3'),
  '22anaparthi.mp3': require('../assets/audio/ST-122/22anaparthi.mp3'),
  '23balabadrapuram.mp3': require('../assets/audio/ST-122/23balabadrapuram.mp3'),
  '24bikkavolu.mp3': require('../assets/audio/ST-122/24bikkavolu.mp3'),
  '25peddabrahmadevam.mp3': require('../assets/audio/ST-122/25peddabrahmadevam.mp3'),
  '26medapadu.mp3': require('../assets/audio/ST-122/26medapadu.mp3'),
  '27veltlapalem.mp3': require('../assets/audio/ST-122/27veltlapalem.mp3'),
  '28samrlakota.mp3': require('../assets/audio/ST-122/28samrlakota.mp3'),
  '29kakinada.mp3': require('../assets/audio/ST-122/29kakinada.mp3'),
}; 